no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = true
low_vram = false

pretrained_model_name_or_path = "gradients-io-tournaments/Z-Image-Turbo"
output_dir = "tournament_z_image_turbo"
output_name = "last"

resolution = "1024,1024"
mixed_precision = "bf16"
train_batch_size = 1  # Z-Image needs more VRAM safety
gradient_accumulation_steps = 16
max_train_epochs = 15

loss_type = "huber"
huber_c = 0.1
huber_schedule = "snr"

optimizer_type = "Prodigy"
optimizer_args = ["weight_decay=0.01", "decouple=True", "use_bias_correction=True", "safeguard_warmup=True", "d_coef=2.0", "growth_rate=1.2"]
unet_lr = 1.0
text_encoder_lr = 1.0
learning_rate = 1.0

network_alpha = 1024
network_dim = 1024
network_module = "networks.lora"
min_snr_gamma = 5.0
seed = 2951032222
