no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = true
low_vram = true  # Forced for Qwen 20B
zero_terminal_snr = true
ip_noise_gamma = 0.1
adaptive_noise_scale = 0.01

pretrained_model_name_or_path = "gradients-io-tournaments/Qwen-Image-Jib-Mix"
output_dir = "tournament_qwen_jib_mix"
output_name = "last"

resolution = "1024,1024"
mixed_precision = "bf16"
train_batch_size = 1
gradient_accumulation_steps = 16
max_train_epochs = 10
no_half_vae = true

loss_type = "huber"
huber_c = 0.1
huber_schedule = "snr"
debiased_estimation_loss = true

optimizer_type = "AdamW8Bit"
optimizer_args = ["weight_decay=0.01", "betas=0.9,0.999"]
learning_rate = 1e-4

noise_offset_type = "Original"
noise_offset = 0.1
multires_noise_iterations = 6
multires_noise_discount = 0.3

network_alpha = 512
network_dim = 512
network_module = "networks.lora"
min_snr_gamma = 5.0
scale_weight_norms = 5
seed = 2951032222
train_data_dir = "img"
